import 'dart:convert';

import 'exports.dart';

/// Generates real Wasm exports around ordinary Dart functions.
String generateBridge(List<Export> exports, String sourceImport) {
  final types = [
    for (final function in exports) ...[
      function.returnType,
      for (final parameter in function.parameters) parameter.type,
    ],
  ];
  final usesLists = types.any((type) => type.kind == ValueKind.listType);
  final usesMaps = types.any((type) => type.kind == ValueKind.mapType);
  final records = <String, ValueType>{
    for (final type in types)
      if (type.kind == ValueKind.recordType) _recordShape(type): type,
  };
  final recordIds = {
    for (final (index, shape) in records.keys.indexed) shape: index,
  };
  final output = StringBuffer()
    ..writeln('// Generated by package:napi. Do not edit.')
    ..writeln("import 'dart:_js_interop_wasm';")
    ..writeln("import 'dart:_wasm';")
    ..writeln("import 'dart:js_interop';")
    ..writeln("import 'dart:typed_data';");
  if (usesMaps) output.writeln("import 'dart:convert';");
  output
    ..writeln('import ${_literal(sourceImport)} as business;')
    ..writeln(_helpers);
  if (usesLists || usesMaps || records.isNotEmpty) {
    output.writeln(_collectionHelpers);
  }
  if (usesLists) output.writeln(_listHelpers);
  if (usesMaps || records.isNotEmpty) output.writeln(_objectHelpers);
  if (usesMaps) output.writeln(_mapHelpers);
  if (records.isNotEmpty) {
    output.writeln(_recordHelpers);
    for (final (index, type) in records.values.indexed) {
      output.writeln(_generateRecord(type, index));
    }
  }
  if (exports.any((function) => function.isAsync)) {
    output.writeln(_promiseHelper);
  }
  for (var index = 0; index < exports.length; index++) {
    final function = exports[index];
    final returnsVoid = function.returnType.kind == ValueKind.voidType;
    final parameters = List.generate(
      function.parameters.length,
      (i) => 'WasmExternRef? raw$i',
    ).join(', ');
    output
      ..writeln("@pragma('wasm:export', ${_literal(function.name)})")
      ..writeln(
        '${returnsVoid && !function.isAsync ? 'WasmVoid' : 'WasmExternRef?'} _export$index($parameters) {',
      )
      ..writeln(function.isAsync ? '  return _promise(() async {' : '  try {');
    for (var i = 0; i < function.parameters.length; i++) {
      final type = function.parameters[i].type;
      output.writeln(
        '    final arg$i = ${type.nullable ? 'raw$i.isNull ? null : ' : ''}${_read(type, 'raw$i', 'parameter ${function.parameters[i].name}', recordIds)};',
      );
    }
    final arguments = List.generate(
      function.parameters.length,
      (i) => 'arg$i',
    ).join(', ');
    final call = 'business.${function.name}($arguments)';
    if (returnsVoid) {
      output
        ..writeln('    ${function.isAsync ? 'await ' : ''}$call;')
        ..writeln('    return ${function.isAsync ? 'null' : 'WasmVoid()'};');
    } else {
      var result = _write(function.returnType, 'result', 'result', recordIds);
      if (function.isAsync) result = '$result!.toJS';
      if (function.returnType.nullable) {
        final nullResult = function.isAsync ? 'null' : 'WasmExternRef.nullRef';
        result = 'result == null ? $nullResult : $result';
      }
      output
        ..writeln(
          '    final result = ${function.isAsync ? 'await ' : ''}$call;',
        )
        ..writeln('    return $result;');
    }
    if (function.isAsync) {
      output.writeln('  }${returnsVoid ? ', returnsVoid: true' : ''});');
    } else {
      output
        ..writeln('  } catch (error, stack) {')
        ..writeln('    _rethrowError(externRefForJSAny(_error(error, stack)));')
        ..writeln(
          '    return ${returnsVoid ? 'WasmVoid()' : 'WasmExternRef.nullRef'};',
        )
        ..writeln('  }');
    }
    output.writeln('}');
  }
  output.writeln('void main() {}');
  return output.toString();
}

String _literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');

String _read(
  ValueType type,
  String value,
  String context,
  Map<String, int> recordIds,
) {
  return switch (type.kind) {
    ValueKind.boolType => '_readBool($value)',
    ValueKind.intType => '_readInt($value)',
    ValueKind.doubleType => '_readDouble($value)',
    ValueKind.stringType => '_readString($value)',
    ValueKind.uint8ListType => '_readBytes($value)',
    ValueKind.listType || ValueKind.mapType =>
      '${type.kind == ValueKind.listType ? '_readList' : '_readMap'}<${_leafType(type.elementType!)}>($value, ${type.elementType!.kind.index}, ${type.elementType!.nullable}, ${_literal(context)})',
    ValueKind.recordType =>
      '_readRecord${recordIds[_recordShape(type)]!}($value, ${_literal(context)})',
    ValueKind.voidType => throw ArgumentError('void parameter'),
  };
}

String _write(
  ValueType type,
  String value,
  String context,
  Map<String, int> recordIds,
) {
  return switch (type.kind) {
    ValueKind.boolType ||
    ValueKind.doubleType ||
    ValueKind.stringType => 'externRefForJSAny($value.toJS)',
    ValueKind.intType => '_writeInt($value)',
    ValueKind.uint8ListType => '_copyBytes(externRefForJSAny($value.toJS))',
    ValueKind.listType || ValueKind.mapType =>
      '${type.kind == ValueKind.listType ? '_writeList' : '_writeMap'}<${_leafType(type.elementType!)}>($value, ${type.elementType!.kind.index}, ${type.elementType!.nullable}, ${_literal(context)})',
    ValueKind.recordType =>
      '_writeRecord${recordIds[_recordShape(type)]!}($value, ${_literal(context)})',
    ValueKind.voidType => throw ArgumentError('void value'),
  };
}

String _leafType(ValueType type) {
  final name = switch (type.kind) {
    ValueKind.boolType => 'bool',
    ValueKind.intType => 'int',
    ValueKind.doubleType => 'double',
    ValueKind.stringType => 'String',
    _ => throw ArgumentError('unsupported collection leaf'),
  };
  return '$name${type.nullable ? '?' : ''}';
}

String _recordShape(ValueType type) => jsonEncode([
  for (final field in type.recordFields)
    [field.name, field.type.kind.index, field.type.nullable],
]);

String _generateRecord(ValueType type, int index) {
  final fields = type.recordFields;
  final recordType =
      '({${fields.map((field) => '${_leafType(field.type)} ${field.name}').join(', ')}})';
  final output = StringBuffer()
    ..writeln(
      'final _recordNames$index = <JSString>[${fields.map((field) => '${_literal(field.name)}.toJS').join(', ')}].toJS;',
    )
    ..writeln(
      '$recordType _readRecord$index(WasmExternRef? value, String context) {',
    )
    ..writeln(
      '  final snapshot = _snapshotRecord(value, externRefForJSAny(_recordNames$index)!, externRefForJSAny(context.toJS));',
    );
  for (final (fieldIndex, field) in fields.indexed) {
    final fieldContext = 'context + ${_literal('[${jsonEncode(field.name)}]')}';
    output.writeln(
      '  final field$fieldIndex = _readRecordField<${_leafType(field.type)}>(snapshot, $fieldIndex, ${field.type.kind.index}, ${field.type.nullable}, $fieldContext);',
    );
  }
  output
    ..writeln(
      '  return (${fields.indexed.map((entry) => '${entry.$2.name}: field${entry.$1}').join(', ')});',
    )
    ..writeln('}')
    ..writeln(
      'WasmExternRef _writeRecord$index($recordType value, String context) {',
    )
    ..writeln('  final result = _newMap();')
    ..writeln('  final names = externRefForJSAny(_recordNames$index)!;');
  for (final (fieldIndex, field) in fields.indexed) {
    final fieldContext = 'context + ${_literal('[${jsonEncode(field.name)}]')}';
    output.writeln(
      '  _writeRecordField(result, _arrayGet(names, WasmI32.fromInt($fieldIndex)), value.${field.name}, ${field.type.kind.index}, ${field.type.nullable}, $fieldContext);',
    );
  }
  output
    ..writeln('  return result;')
    ..writeln('}');
  return output.toString();
}

const _helpers = r'''
@pragma('wasm:import', 'napi.kind')
external WasmI32 _kind(WasmExternRef? value);
@pragma('wasm:import', 'napi.copyBytes')
external WasmExternRef? _copyBytes(WasmExternRef? value);
@pragma('wasm:import', 'napi.error')
external WasmExternRef _createError(WasmI32 kind, WasmExternRef? message, WasmExternRef? stack);
@pragma('wasm:import', 'napi.rethrowError')
external WasmVoid _rethrowError(WasmExternRef? error);

final class _InputError implements Exception {
  const _InputError(this.message);
  final String message;
  @override
  String toString() => message;
}

void _requireType(WasmExternRef? value, int kind, String expected) {
  if (_kind(value).toIntSigned() != kind) {
    throw _InputError('Expected $expected');
  }
}

bool _readBool(WasmExternRef? value) {
  _requireType(value, 2, 'a boolean');
  return (value!.toJS as JSBoolean).toDart;
}

double _readDouble(WasmExternRef? value) {
  _requireType(value, 1, 'a number');
  return (value!.toJS as JSNumber).toDartDouble;
}

const _maxSafeInteger = 9007199254740991;
int _readInt(WasmExternRef? value) {
  final number = _readDouble(value);
  if (!number.isFinite || number != number.truncateToDouble()) {
    throw const _InputError('Expected an integer');
  }
  if (number < -_maxSafeInteger || number > _maxSafeInteger) {
    throw RangeError('Integer must be within the JavaScript safe integer range');
  }
  return number.toInt();
}

String _readString(WasmExternRef? value) {
  _requireType(value, 3, 'a string');
  return (value!.toJS as JSString).toDart;
}

Uint8List _readBytes(WasmExternRef? value) {
  _requireType(value, 4, 'Uint8Array');
  return (_copyBytes(value)!.toJS as JSUint8Array).toDart;
}

WasmExternRef? _writeInt(int value) {
  if (value < -_maxSafeInteger || value > _maxSafeInteger) {
    throw RangeError('Integer must be within the JavaScript safe integer range');
  }
  return externRefForJSAny(value.toDouble().toJS);
}

JSAny _error(Object error, [StackTrace? stack]) {
  if (error is JSAny) return error;
  String message;
  try {
    message = error.toString();
  } catch (_) {
    message = 'Dart exception (toString failed)';
  }
  String? dartStack;
  if (stack != null) {
    try {
      dartStack = stack.toString();
    } catch (_) {
      dartStack = 'Dart stack trace (toString failed)';
    }
  }
  final kind = error is RangeError ? 2
      : error is ArgumentError || error is TypeError || error is _InputError ? 1 : 0;
  return _createError(WasmI32.fromInt(kind), externRefForJSAny(message.toJS),
      dartStack == null ? WasmExternRef.nullRef : externRefForJSAny(dartStack.toJS)).toJS;
}
''';

const _promiseHelper = r'''
WasmExternRef? _promise(Future<JSAny?> Function() invoke, {bool returnsVoid = false}) {
  final promise = JSPromise<JSAny?>((JSFunction resolve, JSFunction reject) {
    // Future.sync invokes immediately: validate and copy inputs before returning.
    Future<JSAny?>.sync(invoke).then<void>(
      (value) {
        if (returnsVoid) {
          resolve.callAsFunction(null);
        } else {
          resolve.callAsFunction(null, value);
        }
      },
      onError: (Object error, StackTrace stack) {
        reject.callAsFunction(null, _error(error, stack));
      },
    );
  }.toJS);
  return externRefForJSAny(promise);
}
''';

const _collectionHelpers = r'''
@pragma('wasm:import', 'napi.arrayLength')
external WasmI32 _arrayLength(WasmExternRef value);
@pragma('wasm:import', 'napi.arrayGet')
external WasmExternRef? _arrayGet(WasmExternRef value, WasmI32 index);
@pragma('wasm:import', 'napi.arraySet')
external WasmVoid _arraySet(WasmExternRef value, WasmI32 index, WasmExternRef? element);

// Raw Wasm values cannot cross ordinary Dart closure trampolines.
T _readLeaf<T>(WasmExternRef? value, int kind, bool nullable) {
  if (nullable && value.isNull) return null as T;
  return (switch (kind) {
    1 => _readBool(value),
    2 => _readInt(value),
    3 => _readDouble(value),
    4 => _readString(value),
    _ => throw StateError('Unsupported collection leaf'),
  }) as T;
}

WasmExternRef? _writeLeaf(Object? value, int kind, bool nullable) {
  if (nullable && value == null) return WasmExternRef.nullRef;
  return switch (kind) {
    1 => externRefForJSAny((value as bool).toJS),
    2 => _writeInt(value as int),
    3 => externRefForJSAny((value as double).toJS),
    4 => externRefForJSAny((value as String).toJS),
    _ => throw StateError('Unsupported collection leaf'),
  };
}

Never _conversionError(Object error, String context) {
  if (error is JSAny) throw error;
  if (error is _InputError) {
    throw _InputError('$context: ${error.message}');
  }
  if (error is RangeError) {
    String message;
    try {
      message = '${error.message}';
    } catch (_) {
      message = 'Dart range error (message formatting failed)';
    }
    throw RangeError('$context: $message');
  }
  if (error is TypeError) {
    String message;
    try {
      message = error.toString();
    } catch (_) {
      message = 'Dart type error (toString failed)';
    }
    throw _InputError('$context: $message');
  }
  throw error;
}
''';

const _listHelpers = r'''
@pragma('wasm:import', 'napi.snapshotList')
external WasmExternRef _snapshotList(WasmExternRef? value, WasmExternRef? context);
@pragma('wasm:import', 'napi.newList')
external WasmExternRef _newList(WasmI32 length);

List<T> _readList<T>(WasmExternRef? value, int kind, bool nullable, String context) {
  final snapshot = _snapshotList(value, externRefForJSAny(context.toJS));
  final length = _arrayLength(snapshot).toIntUnsigned();
  final result = <T>[];
  var index = 0;
  try {
    for (; index < length; index++) {
      result.add(_readLeaf<T>(_arrayGet(snapshot, WasmI32.fromInt(index)), kind, nullable));
    }
  } catch (error) {
    _conversionError(error, '$context[$index]');
  }
  return result;
}

WasmExternRef _writeList<T>(List<T> value, int kind, bool nullable, String context) {
  var index = 0;
  try {
    final length = value.length;
    final result = _newList(WasmI32.fromInt(length));
    for (; index < length; index++) {
      _arraySet(result, WasmI32.fromInt(index), _writeLeaf(value[index], kind, nullable));
    }
    return result;
  } catch (error) {
    _conversionError(error, '$context[$index]');
  }
}
''';

const _objectHelpers = r'''
@pragma('wasm:import', 'napi.newMap')
external WasmExternRef _newMap();
@pragma('wasm:import', 'napi.mapSet')
external WasmVoid _mapSet(WasmExternRef value, WasmExternRef? key, WasmExternRef? element);
''';

const _mapHelpers = r'''
@pragma('wasm:import', 'napi.snapshotMap')
external WasmExternRef _snapshotMap(WasmExternRef? value, WasmExternRef? context);

Map<String, T> _readMap<T>(WasmExternRef? value, int kind, bool nullable, String context) {
  final snapshot = _snapshotMap(value, externRefForJSAny(context.toJS));
  final length = _arrayLength(snapshot).toIntUnsigned();
  final result = <String, T>{};
  String? key;
  try {
    for (var index = 0; index < length; index += 2) {
      key = _readString(_arrayGet(snapshot, WasmI32.fromInt(index)));
      result[key] = _readLeaf<T>(_arrayGet(snapshot, WasmI32.fromInt(index + 1)), kind, nullable);
    }
  } catch (error) {
    _conversionError(error, key == null ? context : '$context[${jsonEncode(key)}]');
  }
  return result;
}

WasmExternRef _writeMap<T>(Map<String, T> value, int kind, bool nullable, String context) {
  final result = _newMap();
  String? key;
  try {
    for (final entry in value.entries) {
      key = entry.key;
      _mapSet(result, externRefForJSAny(key.toJS), _writeLeaf(entry.value, kind, nullable));
    }
  } catch (error) {
    _conversionError(error, key == null ? context : '$context[${jsonEncode(key)}]');
  }
  return result;
}
''';

const _recordHelpers = r'''
@pragma('wasm:import', 'napi.snapshotRecord')
external WasmExternRef _snapshotRecord(WasmExternRef? value, WasmExternRef names, WasmExternRef? context);

T _readRecordField<T>(WasmExternRef snapshot, int index, int kind, bool nullable, String context) {
  try {
    return _readLeaf<T>(_arrayGet(snapshot, WasmI32.fromInt(index)), kind, nullable);
  } catch (error) {
    _conversionError(error, context);
  }
}

void _writeRecordField(WasmExternRef result, WasmExternRef? key, Object? value, int kind, bool nullable, String context) {
  try {
    _mapSet(result, key, _writeLeaf(value, kind, nullable));
  } catch (error) {
    _conversionError(error, context);
  }
}
''';
