import 'dart:convert';

import 'exports.dart';

/// Generates raw wasm32 Node-API entrypoints around ordinary Dart functions.
String generateBridge(List<Export> exports, String sourceImport) {
  final output = StringBuffer()
    ..writeln("// Generated by package:napi. Do not edit.")
    ..writeln("import 'dart:_wasm';")
    ..writeln("import 'dart:convert';")
    ..writeln("import 'dart:typed_data';")
    ..writeln('import ${_literal(sourceImport)} as business;')
    ..writeln(_helpers);
  for (var index = 0; index < exports.length; index++) {
    final function = exports[index];
    output
      ..writeln("@pragma('wasm:export', 'napi_dart_callback_$index')")
      ..writeln('WasmI32 _callback$index(WasmI32 rawEnv, WasmI32 info) {')
      ..writeln('  final env = rawEnv.toIntUnsigned();')
      ..writeln('  try {')
      ..writeln(
        '    final arguments = _arguments(env, info.toIntUnsigned(), ${function.parameters.length});',
      );
    for (
      var parameter = 0;
      parameter < function.parameters.length;
      parameter++
    ) {
      final type = function.parameters[parameter].type;
      final handle = 'arguments[$parameter]';
      final read = _read(type.kind, handle);
      output.writeln(
        '    final arg$parameter = ${type.nullable ? '_isNull(env, $handle) ? null : $read' : read};',
      );
    }
    final arguments = List.generate(
      function.parameters.length,
      (i) => 'arg$i',
    ).join(', ');
    final call = 'business.${function.name}($arguments)';
    if (function.returnType.kind == ValueKind.voidType) {
      output
        ..writeln('    $call;')
        ..writeln('    return _undefined(env);');
    } else {
      output
        ..writeln('    final result = $call;')
        ..writeln(
          '    return ${function.returnType.nullable ? 'result == null ? _null(env) : ' : ''}${_write(function.returnType.kind, 'result')};',
        );
    }
    output
      ..writeln('  } catch (error) {')
      ..writeln('    _throwException(env, error);')
      ..writeln('    return _i32(0);')
      ..writeln('  }')
      ..writeln('}');
  }
  output
    ..writeln("@pragma('wasm:export', 'napi_register_wasm_v1')")
    ..writeln('WasmI32 _register(WasmI32 rawEnv, WasmI32 rawExports) {')
    ..writeln('  final env = rawEnv.toIntUnsigned();')
    ..writeln('  final exports = rawExports.toIntUnsigned();')
    ..writeln('  try {');
  for (var index = 0; index < exports.length; index++) {
    output.writeln(
      '    _registerFunction(env, exports, ${_literal(exports[index].name)}, ${index + 1});',
    );
  }
  output
    ..writeln('    return rawExports;')
    ..writeln('  } catch (error) {')
    ..writeln('    _throwException(env, error);')
    ..writeln('    return _i32(0);')
    ..writeln('  }')
    ..writeln('}')
    ..writeln('void main() {}');
  return output.toString();
}

String _literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');

String _read(ValueKind kind, String handle) => switch (kind) {
  ValueKind.boolType => '_readBool(env, $handle)',
  ValueKind.intType => '_readInt(env, $handle)',
  ValueKind.doubleType => '_readDouble(env, $handle)',
  ValueKind.stringType => '_readString(env, $handle)',
  ValueKind.uint8ListType => '_readBytes(env, $handle)',
  ValueKind.voidType => throw ArgumentError('void parameter'),
};

String _write(ValueKind kind, String value) => switch (kind) {
  ValueKind.boolType => '_writeBool(env, $value)',
  ValueKind.intType => '_writeInt(env, $value)',
  ValueKind.doubleType => '_writeDouble(env, $value)',
  ValueKind.stringType => '_writeString(env, $value)',
  ValueKind.uint8ListType => '_writeBytes(env, $value)',
  ValueKind.voidType => '_undefined(env)',
};

const _helpers = r'''
@pragma('wasm:memory-type', MemoryType(limits: Limits(1, 32768)))
@pragma('wasm:import', 'env.memory')
external Memory get _memory;
@pragma('wasm:import', 'env.napi_dart_allocate')
external WasmI32 _allocateRaw(WasmI32 size);
@pragma('wasm:import', 'env.napi_create_function')
external WasmI32 _createFunction(WasmI32 env, WasmI32 name, WasmI32 length, WasmI32 callback, WasmI32 data, WasmI32 result);
@pragma('wasm:import', 'env.napi_set_named_property')
external WasmI32 _setNamedProperty(WasmI32 env, WasmI32 object, WasmI32 name, WasmI32 value);
@pragma('wasm:import', 'env.napi_get_cb_info')
external WasmI32 _getCallbackInfo(WasmI32 env, WasmI32 info, WasmI32 argc, WasmI32 argv, WasmI32 receiver, WasmI32 data);
@pragma('wasm:import', 'env.napi_typeof')
external WasmI32 _typeOf(WasmI32 env, WasmI32 value, WasmI32 result);
@pragma('wasm:import', 'env.napi_get_value_bool')
external WasmI32 _getBool(WasmI32 env, WasmI32 value, WasmI32 result);
@pragma('wasm:import', 'env.napi_get_value_double')
external WasmI32 _getDouble(WasmI32 env, WasmI32 value, WasmI32 result);
@pragma('wasm:import', 'env.napi_get_boolean')
external WasmI32 _createBool(WasmI32 env, WasmI32 value, WasmI32 result);
@pragma('wasm:import', 'env.napi_create_double')
external WasmI32 _createDouble(WasmI32 env, WasmF64 value, WasmI32 result);
@pragma('wasm:import', 'env.napi_get_null')
external WasmI32 _getNull(WasmI32 env, WasmI32 result);
@pragma('wasm:import', 'env.napi_get_undefined')
external WasmI32 _getUndefined(WasmI32 env, WasmI32 result);
@pragma('wasm:import', 'env.napi_get_value_string_utf16')
external WasmI32 _getString(WasmI32 env, WasmI32 value, WasmI32 buffer, WasmI32 length, WasmI32 result);
@pragma('wasm:import', 'env.napi_create_string_utf16')
external WasmI32 _createString(WasmI32 env, WasmI32 buffer, WasmI32 length, WasmI32 result);
@pragma('wasm:import', 'env.napi_get_typedarray_info')
external WasmI32 _getTypedArray(WasmI32 env, WasmI32 value, WasmI32 type, WasmI32 length, WasmI32 data, WasmI32 arraybuffer, WasmI32 byteOffset);
@pragma('wasm:import', 'env.napi_create_arraybuffer')
external WasmI32 _createArrayBuffer(WasmI32 env, WasmI32 length, WasmI32 data, WasmI32 result);
@pragma('wasm:import', 'env.napi_create_typedarray')
external WasmI32 _createTypedArray(WasmI32 env, WasmI32 type, WasmI32 length, WasmI32 arraybuffer, WasmI32 offset, WasmI32 result);
@pragma('wasm:import', 'env.napi_throw_type_error')
external WasmI32 _throwTypeError(WasmI32 env, WasmI32 code, WasmI32 message);
@pragma('wasm:import', 'env.napi_throw_range_error')
external WasmI32 _throwRangeError(WasmI32 env, WasmI32 code, WasmI32 message);
@pragma('wasm:import', 'env.napi_throw_error')
external WasmI32 _throwError(WasmI32 env, WasmI32 code, WasmI32 message);

WasmI32 _i32(int value) => WasmI32.fromInt(value);
int _allocate(int size) {
  if (size < 0 || size > 0x7ffffff0)
    throw RangeError('Node-API allocation is too large');
  final pointer = _allocateRaw(_i32(size)).toIntUnsigned();
  if (pointer == 0) throw StateError('Node-API allocation failed');
  return pointer;
}
final class _InputError implements Exception {
  const _InputError(this.message);
  final String message;
  @override
  String toString() => message;
}
void _check(WasmI32 status) {
  if (status.toIntSigned() != 0) throw const _InputError('Unexpected JavaScript argument type');
}
List<int> _arguments(int env, int info, int expected) {
  final argc = _allocate(4);
  final argv = expected == 0 ? 0 : _allocate(expected * 4);
  _memory.storeInt32(argc, _i32(expected));
  _check(_getCallbackInfo(_i32(env), _i32(info), _i32(argc), _i32(argv), _i32(0), _i32(0)));
  if (_memory.loadInt32(argc).toIntUnsigned() != expected)
    throw _InputError('Expected exactly $expected positional arguments');
  return List.generate(expected, (index) => _memory.loadInt32(argv + index * 4).toIntUnsigned());
}
bool _isNull(int env, int value) {
  final result = _allocate(4);
  _check(_typeOf(_i32(env), _i32(value), _i32(result)));
  return _memory.loadInt32(result).toIntSigned() == 1;
}
bool _readBool(int env, int value) {
  final result = _allocate(1);
  _check(_getBool(_i32(env), _i32(value), _i32(result)));
  return _memory.loadUint8(result).toIntUnsigned() != 0;
}
double _readDouble(int env, int value) {
  final result = _allocate(8);
  _check(_getDouble(_i32(env), _i32(value), _i32(result)));
  return _memory.loadFloat64(result).toDouble();
}
const _maxSafeInteger = 9007199254740991;
int _readInt(int env, int value) {
  final number = _readDouble(env, value);
  if (!number.isFinite || number != number.truncateToDouble())
    throw const _InputError('Expected an integer');
  if (number < -_maxSafeInteger || number > _maxSafeInteger)
    throw RangeError('Integer must be within the JavaScript safe integer range');
  return number.toInt();
}
String _readString(int env, int value) {
  final count = _allocate(4);
  _check(_getString(_i32(env), _i32(value), _i32(0), _i32(0), _i32(count)));
  final length = _memory.loadInt32(count).toIntUnsigned();
  final data = _allocate((length + 1) * 2);
  _check(_getString(_i32(env), _i32(value), _i32(data), _i32(length + 1), _i32(count)));
  return String.fromCharCodes(List.generate(length, (index) => _memory.loadUint16(data + index * 2).toIntUnsigned()));
}
Uint8List _readBytes(int env, int value) {
  final type = _allocate(4);
  final count = _allocate(4);
  final pointer = _allocate(4);
  _check(_getTypedArray(_i32(env), _i32(value), _i32(type), _i32(count), _i32(pointer), _i32(0), _i32(0)));
  if (_memory.loadInt32(type).toIntSigned() != 1)
    throw const _InputError('Expected Uint8Array');
  final length = _memory.loadInt32(count).toIntUnsigned();
  final data = _memory.loadInt32(pointer).toIntUnsigned();
  final result = Uint8List(length);
  for (var index = 0; index < length; index++) result[index] = _memory.loadUint8(data + index).toIntUnsigned();
  return result;
}
WasmI32 _null(int env) {
  final result = _allocate(4);
  _check(_getNull(_i32(env), _i32(result)));
  return _memory.loadInt32(result);
}
WasmI32 _undefined(int env) {
  final result = _allocate(4);
  _check(_getUndefined(_i32(env), _i32(result)));
  return _memory.loadInt32(result);
}
WasmI32 _writeBool(int env, bool value) {
  final result = _allocate(4);
  _check(_createBool(_i32(env), _i32(value ? 1 : 0), _i32(result)));
  return _memory.loadInt32(result);
}
WasmI32 _writeDouble(int env, double value) {
  final result = _allocate(4);
  _check(_createDouble(_i32(env), WasmF64.fromDouble(value), _i32(result)));
  return _memory.loadInt32(result);
}
WasmI32 _writeInt(int env, int value) {
  if (value < -_maxSafeInteger || value > _maxSafeInteger)
    throw RangeError('Integer must be within the JavaScript safe integer range');
  return _writeDouble(env, value.toDouble());
}
WasmI32 _writeString(int env, String value) {
  final pointer = _allocate((value.length + 1) * 2);
  for (var index = 0; index < value.length; index++) _memory.storeInt16(pointer + index * 2, _i32(value.codeUnitAt(index)));
  _memory.storeInt16(pointer + value.length * 2, _i32(0));
  final result = _allocate(4);
  _check(_createString(_i32(env), _i32(pointer), _i32(value.length), _i32(result)));
  return _memory.loadInt32(result);
}
WasmI32 _writeBytes(int env, Uint8List value) {
  final pointer = _allocate(4);
  final arraybufferResult = _allocate(4);
  _check(_createArrayBuffer(_i32(env), _i32(value.length), _i32(pointer), _i32(arraybufferResult)));
  final arraybuffer = _memory.loadInt32(arraybufferResult);
  final data = _memory.loadInt32(pointer).toIntUnsigned();
  for (var index = 0; index < value.length; index++) _memory.storeInt8(data + index, _i32(value[index]));
  final result = _allocate(4);
  _check(_createTypedArray(_i32(env), _i32(1), _i32(value.length), arraybuffer, _i32(0), _i32(result)));
  return _memory.loadInt32(result);
}
int _utf8(String value) {
  final encoded = utf8.encode(value);
  final pointer = _allocate(encoded.length + 1);
  for (var index = 0; index < encoded.length; index++) _memory.storeInt8(pointer + index, _i32(encoded[index]));
  _memory.storeInt8(pointer + encoded.length, _i32(0));
  return pointer;
}
void _throwException(int env, Object error) {
  final message = _i32(_utf8(error.toString()));
  if (error is RangeError) {
    _throwRangeError(_i32(env), _i32(0), message);
  } else if (error is ArgumentError || error is _InputError) {
    _throwTypeError(_i32(env), _i32(0), message);
  } else {
    _throwError(_i32(env), _i32(0), message);
  }
}
void _registerFunction(int env, int exports, String name, int callback) {
  final pointer = _utf8(name);
  final result = _allocate(4);
  _check(_createFunction(_i32(env), _i32(pointer), _i32(-1), _i32(callback), _i32(0), _i32(result)));
  final function = _memory.loadInt32(result);
  _check(_setNamedProperty(_i32(env), _i32(exports), _i32(pointer), function));
}
''';
