import 'dart:convert';

import 'exports.dart';

/// Generates real Wasm exports around ordinary Dart functions.
String generateBridge(List<Export> exports, String sourceImport) {
  final output = StringBuffer()
    ..writeln('// Generated by package:napi. Do not edit.')
    ..writeln("import 'dart:_js_interop_wasm';")
    ..writeln("import 'dart:_wasm';")
    ..writeln("import 'dart:js_interop';")
    ..writeln("import 'dart:typed_data';")
    ..writeln('import ${_literal(sourceImport)} as business;')
    ..writeln(_helpers);
  if (exports.any((function) => function.isAsync)) {
    output.writeln(_promiseHelper);
  }
  for (var index = 0; index < exports.length; index++) {
    final function = exports[index];
    final returnsVoid = function.returnType.kind == ValueKind.voidType;
    final parameters = List.generate(
      function.parameters.length,
      (i) => 'WasmExternRef? raw$i',
    ).join(', ');
    output
      ..writeln("@pragma('wasm:export', ${_literal(function.name)})")
      ..writeln(
        '${returnsVoid && !function.isAsync ? 'WasmVoid' : 'WasmExternRef?'} _export$index($parameters) {',
      )
      ..writeln(function.isAsync ? '  return _promise(() async {' : '  try {');
    for (var i = 0; i < function.parameters.length; i++) {
      final type = function.parameters[i].type;
      output.writeln(
        '    final arg$i = ${type.nullable ? 'raw$i.isNull ? null : ' : ''}${_read(type.kind, 'raw$i')};',
      );
    }
    final arguments = List.generate(
      function.parameters.length,
      (i) => 'arg$i',
    ).join(', ');
    final call = 'business.${function.name}($arguments)';
    if (returnsVoid) {
      output
        ..writeln('    ${function.isAsync ? 'await ' : ''}$call;')
        ..writeln('    return ${function.isAsync ? 'null' : 'WasmVoid()'};');
    } else {
      var result = _write(function.returnType.kind, 'result');
      if (function.isAsync) result = '$result!.toJS';
      if (function.returnType.nullable) {
        final nullResult = function.isAsync ? 'null' : 'WasmExternRef.nullRef';
        result = 'result == null ? $nullResult : $result';
      }
      output
        ..writeln(
          '    final result = ${function.isAsync ? 'await ' : ''}$call;',
        )
        ..writeln('    return $result;');
    }
    if (function.isAsync) {
      output.writeln('  }${returnsVoid ? ', returnsVoid: true' : ''});');
    } else {
      output
        ..writeln('  } catch (error, stack) {')
        ..writeln('    _rethrowError(externRefForJSAny(_error(error, stack)));')
        ..writeln(
          '    return ${returnsVoid ? 'WasmVoid()' : 'WasmExternRef.nullRef'};',
        )
        ..writeln('  }');
    }
    output.writeln('}');
  }
  output.writeln('void main() {}');
  return output.toString();
}

String _literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');

String _read(ValueKind kind, String value) => switch (kind) {
  ValueKind.boolType => '_readBool($value)',
  ValueKind.intType => '_readInt($value)',
  ValueKind.doubleType => '_readDouble($value)',
  ValueKind.stringType => '_readString($value)',
  ValueKind.uint8ListType => '_readBytes($value)',
  ValueKind.voidType => throw ArgumentError('void parameter'),
};

String _write(ValueKind kind, String value) => switch (kind) {
  ValueKind.boolType ||
  ValueKind.doubleType ||
  ValueKind.stringType => 'externRefForJSAny($value.toJS)',
  ValueKind.intType => '_writeInt($value)',
  ValueKind.uint8ListType => '_copyBytes(externRefForJSAny($value.toJS))',
  ValueKind.voidType => throw ArgumentError('void value'),
};

const _helpers = r'''
@pragma('wasm:import', 'napi.kind')
external WasmI32 _kind(WasmExternRef? value);
@pragma('wasm:import', 'napi.copyBytes')
external WasmExternRef? _copyBytes(WasmExternRef? value);
@pragma('wasm:import', 'napi.error')
external WasmExternRef _createError(WasmI32 kind, WasmExternRef? message, WasmExternRef? stack);
@pragma('wasm:import', 'napi.rethrowError')
external WasmVoid _rethrowError(WasmExternRef? error);

final class _InputError implements Exception {
  const _InputError(this.message);
  final String message;
  @override
  String toString() => message;
}

void _requireType(WasmExternRef? value, int kind, String expected) {
  if (_kind(value).toIntSigned() != kind) {
    throw _InputError('Expected $expected');
  }
}

bool _readBool(WasmExternRef? value) {
  _requireType(value, 2, 'a boolean');
  return (value!.toJS as JSBoolean).toDart;
}

double _readDouble(WasmExternRef? value) {
  _requireType(value, 1, 'a number');
  return (value!.toJS as JSNumber).toDartDouble;
}

const _maxSafeInteger = 9007199254740991;
int _readInt(WasmExternRef? value) {
  final number = _readDouble(value);
  if (!number.isFinite || number != number.truncateToDouble()) {
    throw const _InputError('Expected an integer');
  }
  if (number < -_maxSafeInteger || number > _maxSafeInteger) {
    throw RangeError('Integer must be within the JavaScript safe integer range');
  }
  return number.toInt();
}

String _readString(WasmExternRef? value) {
  _requireType(value, 3, 'a string');
  return (value!.toJS as JSString).toDart;
}

Uint8List _readBytes(WasmExternRef? value) {
  _requireType(value, 4, 'Uint8Array');
  return (_copyBytes(value)!.toJS as JSUint8Array).toDart;
}

WasmExternRef? _writeInt(int value) {
  if (value < -_maxSafeInteger || value > _maxSafeInteger) {
    throw RangeError('Integer must be within the JavaScript safe integer range');
  }
  return externRefForJSAny(value.toDouble().toJS);
}

JSAny _error(Object error, [StackTrace? stack]) {
  if (error is JSAny) return error;
  String message;
  try {
    message = error.toString();
  } catch (_) {
    message = 'Dart exception (toString failed)';
  }
  String? dartStack;
  if (stack != null) {
    try {
      dartStack = stack.toString();
    } catch (_) {
      dartStack = 'Dart stack trace (toString failed)';
    }
  }
  final kind = error is RangeError ? 2
      : error is ArgumentError || error is TypeError || error is _InputError ? 1 : 0;
  return _createError(WasmI32.fromInt(kind), externRefForJSAny(message.toJS),
      dartStack == null ? WasmExternRef.nullRef : externRefForJSAny(dartStack.toJS)).toJS;
}
''';

const _promiseHelper = r'''
WasmExternRef? _promise(Future<JSAny?> Function() invoke, {bool returnsVoid = false}) {
  final promise = JSPromise<JSAny?>((JSFunction resolve, JSFunction reject) {
    // Future.sync invokes immediately: validate and copy inputs before returning.
    Future<JSAny?>.sync(invoke).then<void>(
      (value) {
        if (returnsVoid) {
          resolve.callAsFunction(null);
        } else {
          resolve.callAsFunction(null, value);
        }
      },
      onError: (Object error, StackTrace stack) {
        reject.callAsFunction(null, _error(error, stack));
      },
    );
  }.toJS);
  return externRefForJSAny(promise);
}
''';
